name: terraform deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haythem/public-ip@v1.3
      - run: ${{ steps.ip.outputs.ipv4 }}
      - uses: hashicorp/setup-terraform@v2
      - run: echo "${{ secrets.TERRAFORM_SA }}" | base64 -d  > .terraform.sa.json
      - run: echo "${{ secrets.TERRAFORM_SA_STATIC }}" | base64 -d  > .terraform.sa.static.json
      - run: |
          jq -r '.+{allowed_ip:"\(.allowed_ip),${{ steps.ip.outputs.ipv4 }}"}' > .terraform.config.json << EOF
          ${{ vars.TERRAFORM_CONFIG }}
          EOF
      - run: make deploy
